### ISSUE TITLE
Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by yceruto** [jeremeamia/super_closure#94]
Hi, first thank you for this awesome library!

I've a problem serializing this context:
```
$options['foo'] = function () {
    // do something.
};

$serializable = (new Serializer)->serialize(function () use ($options) {
    // do something.
});

// throws: Serialization of closure failed: Serialization of 'Closure' is not allowed
```
It could happen in `$this` context too. Any suggestion?

**Comment by GrahamCampbell** [comment]
This is because you cannot use closures as variables to bind to closures. Could be messy for us to try to serialize those too. Feel free to try to implement that and let us know how you get on. Alternatively, @jeremeamia might know more on this subject. I don't know if implementing that is something already considered, but decided against?

**Comment by yceruto** [comment]
@GrahamCampbell

>This is because you cannot use closures as variables to bound to closures.

 I've displayed only a sample of the real context. I'm using this into a Symfony controller and I can't use `$this` for instance, because it contains objects/dependencies with similar situation. Also, these instances/objects are initialized by the framework/third-party.

**Comment by jeremeamia** [comment]
You could try `Serializer::wrapClosures()`. It's not battle-tested, but it's intent is that you can throw anything at it, and it will attempt to wrap all the closures inside to be serializeable. Any objects nested inside are hopefully serializable in their own right.

**Comment by yceruto** [comment]
@jeremeamia Thank you, I'll try this.
